# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(default='')),
                ('event_detail', models.TextField(default='')),
                ('event_numset', models.TextField(default='')),
                ('event_location', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(default='')),
                ('lname', models.TextField(default='')),
                ('pcount', models.TextField(default='')),
            ],
        ),
    ]
