# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170422_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pcount',
        ),
        migrations.AddField(
            model_name='event',
            name='pcount',
            field=models.IntegerField(default=0),
        ),
    ]
