# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20170422_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
